<!DOCTYPE html>
<html>

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>{{ __('employees.advance_salaries') . ' ' . now()->IsoFormat('LL')}}</title>

    <style type="text/css">
        @page {
            margin: 0cm 0cm;
        }

        /** Define now the real margins of every page in the PDF **/
        body {
            margin-top: 1cm;
            margin-left: 1cm;
            margin-right: 1cm;
            margin-bottom: 1cm;
        }

        /** Define the header rules **/
        header {
            position: fixed;
            top: 0cm;
            left: 0cm;
            right: 0cm;
            height: 0.1cm;

            /** Extra personal styles **/
            background-color: #17469E;
        }

        /** Define the footer rules **/
        footer {
            position: fixed;
            bottom: 0cm;
            left: 0cm;
            right: 0cm;
            height: 2cm;

            /** Extra personal styles **/
            text-align: center;
            font-size: medium;
            line-height: 1.5cm;
            border-bottom: 2px solid #17469E;
        }

        .heading {
            font-family: Arial, Helvetica, sans-serif;
            font-size: 22px;
            font-weight: 800;
            padding-bottom: 0;
        }

        .sub-heading {
            font-family: Arial, Helvetica, sans-serif;
            font-size: 14px;
            font-weight: 500;
            padding-bottom: 2px;
        }

        .badge {
            display: inline-block;
            padding: 0.35em 0.65em;
            font-size: .75em;
            font-weight: 400;
            line-height: 1;
            color: #fff;
            text-align: center;
            white-space: nowrap;
            vertical-align: baseline;
            border-radius: 0.25rem;
        }

        .bg-danger {
            background-color: #d32f2f !important;
        }

        .bg-success {
            background-color: #2e7d32 !important;
        }

        .bg-warning {
            background-color: #ffb300 !important;
        }

        .bg-primary {
            background-color: #17469E !important;
        }

        .text-white {
            color: white;
        }

        .table {
            font-family: Arial, Helvetica, sans-serif;
            font-size: 13px;
            border-collapse: collapse;
            width: 100%;
        }

        td,
        th {
            border: 1px solid #ddd;
            padding: 8px;
        }

        tr:nth-child(even) {
            background-color: #f2f2f2;
        }

        .table th {
            padding-top: 10px;
            padding-bottom: 10px;
            text-align: left;
            background-color: #17469E;
            color: white;
        }

        .summary-table {
            font-family: Arial, Helvetica, sans-serif;
            font-size: 13px;
            border-collapse: collapse;
            width: 80%;
        }

        .summary-table td,
        .summary-table th {
            border: 1px solid #ddd;
            text-align: left;
        }

        .fs-bold {
            font-weight: 600;
            font-size: 18px;
        }

        .text-underline {
            text-decoration: underline;
        }
    </style>
</head>

<body>
    <header>
    </header>


    <footer>
        <p class=''>{{__('Generated By - '). auth()->user()->name}} {{__('on the ')}} - {{__('Copyright')}} &copy; Ciblerh-Checkin {{now()->year}}</p>
    </footer>


    <div class=''>
        <div class='' style="padding-bottom: 10px;">
            <div style="float: left; width: 40%; ">
                <img src="{{'data:image/png;base64,'.base64_encode(file_get_contents(public_path('img/logo.jpg')))}}" alt='' style="width:auto;height:100px;">
            </div>

            <p style="margin-left: 80%; width: 20%; font-weight:bold;">
                <br />{{__('Ref:R2 FM.07d')}}
                <br />{{__('Creation Date')}}
                <br>{{__('09/09/2019')}}
            </p>
        </div>
        <p class="text-underline" style="text-align: center; font-weight:bolder; ">{{__("DEMAND D'ACOMPTE SUR SALAIRE")}}</p>
        <p>
            <span style="font-weight:bolder">{{__("First and last name")}}:</span>
            <span class='text-underline'>
                {{$advance_salary->user->name}}
            </span>
        </p>
        <p>
            <span style="font-weight:bolder">{{__("Position")}}:</span>
            <span class='text-underline'> {{$advance_salary->user->position}}</span>
        </p>
        <p>
            <span style="font-weight:bolder">{{__("User Company")}}:</span>
            <span class='text-underline'>{{$advance_salary->user->company->name}}</span>
        </p>
        <p>
            <span style="font-weight:bolder">{{__("Amount requested (in figures and letters)")}}:</span>
            <span class='text-underline'> {{number_format($advance_salary->amount)}} {{__("francs")}} ({{$advance_salary->amount_in_words ." ". __("francs")}})</span>
        </p>
        <p>
            <span style="font-weight:bolder">{{__("To be deducted from the salary (for the month of)")}}:</span>
            <span class='text-underline'>{{$advance_salary->repayment_from_month->format('Y-m')}}</span>
            {{__("to")}}
            <span class='text-underline'>{{$advance_salary->repayment_to_month->format('Y-m')}}</span>
        </p>
        <p>
            <span style="font-weight:bolder">{{__("Motive")}}:</span>
            <span class='text-underline'> {{$advance_salary->reason}}</span>
        </p>
        <p style="text-align: center; ">{{__("Modalites de paiement : Montant superieur 30,000frs")}}</p>
        <p style="text-align: center;font-weight:bolder;">{{__("BENEFICIARE")}}</p>
        <p>
            <span style="font-weight:bolder">{{__("Name of beneficiary")}}:</span>
            <span class='text-underline'>{{$advance_salary->beneficiary_name}}</span>
        </p>
        <p>
            <span style="font-weight:bolder">{{__("Mobile Money Number")}}:</span>
            <span class='text-underline'>{{$advance_salary->beneficiary_mobile_money_number}}</span>
        </p>
        <p>
            <span style="font-weight:bolder">{{__("ID card Number")}}:</span>
            <span class='text-underline'>{{$advance_salary->beneficiary_id_card_number}}</span>
        </p>
        <!-- <p>
            <span style="font-weight:bolder">{{__("Motif:")}}</span>
            <span class='text-underline'>{{$advance_salary->reason}}</span>
        </p> -->

        <p>
            <span style="font-weight:bolder; padding: 10px, 0;">{{__("Net Salary")}}: </span>
            <span class='text-underline'>{{number_format($advance_salary->user->net_salary)}} {{__("XAF")}}</span>
        </p>
        <p>
            <span style="font-weight:bolder; padding: 10px, 0;">{{__("Portfolio Manager Reviews")}}</span>
            @if($advance_salary->approval_status === 1)
            <span class="badge text-white bg-success">{{__('common.approved')}}</span>
            @elseif ($advance_salary->approval_status === 2)
            <span class="badge bg-danger text-white">{{__('common.rejected')}}</span>
            @else
            <span class="badge bg-warning text-white">{{__('common.pending')}}</span>
            @endif
        </p>
        <table class="table">
            <thead class="">
                <tr>
                    <th></th>
                    <th>{{ __('Requestor') }}</th>
                    <th>{{ __('Audit/Internal Controller') }}</th>
                    <th>{{ __('DGA/DG') }}</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>{{__("First and Last Names")}}</td>
                    <td>{{$advance_salary->user->name}}</td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <td>{{__("Signature")}}</td>
                    <td>{{__('common.approved')}}</td>
                    <td></td>
                    <td></td>
                </tr>
            </tbody>
        </table>

    </div>
</body>

</html>