<!DOCTYPE html>
<html>

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>{{ __('Checkin Report').now()->IsoFormat('LL')}}</title>

    <style type="text/css">
        @page {
            margin: 0cm 0cm;
        }

        /** Define now the real margins of every page in the PDF **/
        body {
            margin-top: 0.3cm;
            margin-left: 0.5cm;
            margin-right: 0.5cm;
            margin-bottom: 0cm;
        }

        /** Define the header rules **/
        header {
            position: fixed;
            top: 0cm;
            left: 0cm;
            right: 0cm;
            height: 0.1cm;

            /** Extra personal styles **/
            background-color: #17469E;
        }

        /** Define the footer rules **/
        footer {
            position: fixed;
            bottom: 0cm;
            left: 0cm;
            right: 0cm;
            height: 2cm;

            /** Extra personal styles **/
            text-align: center;
            font-size: medium;
            line-height: 1.5cm;
            border-bottom: 2px solid #17469E;
        }

        .iso-logo {
            position: fixed;
            bottom: 2cm;
            right: .8cm;
            height: 3.1cm;
        }

        .heading {
            font-family: Arial, Helvetica, sans-serif;
            font-size: 22px;
            font-weight: 800;
            padding-bottom: 0;
        }

        .sub-heading {
            font-family: Arial, Helvetica, sans-serif;
            font-size: 14px;
            font-weight: 500;
            padding-bottom: 2px;
        }

        .badge {
            display: inline-block;
            padding: 0.35em 0.65em;
            font-size: .75em;
            font-weight: 400;
            line-height: 1;
            color: #fff;
            text-align: center;
            white-space: nowrap;
            vertical-align: baseline;
            border-radius: 0.25rem;
        }

        .bg-danger {
            background-color: #d32f2f !important;
        }

        .bg-success {
            background-color: #2e7d32 !important;
        }

        .bg-warning {
            background-color: #ffb300 !important;
        }

        .bg-primary {
            background-color: #17469E !important;
        }

        .text-white {
            color: white;
        }

        .table {
            font-family: Arial, Helvetica, sans-serif;
            font-size: 13px;
            border-collapse: collapse;
            width: 100%;
        }

        td,
        th {
            border: 1px solid #ddd;
            padding: 8px;
        }

        tr:nth-child(even) {
            background-color: #f2f2f2;
        }

        .table th {
            padding-top: 10px;
            padding-bottom: 10px;
            text-align: left;
            background-color: #17469E;
            color: white;
        }

        .summary-table {
            font-family: Arial, Helvetica, sans-serif;
            font-size: 13px;
            border-collapse: collapse;
            width: 80%;
        }

        .summary-table td,
        .summary-table th {
            border: 1px solid #ddd;
            text-align: left;
        }

        .fs-bold {
            font-weight: 600;
            font-size: 18px;
        }

        .w-25 {
            width: 15%;
        }

        .h-25 {
            height: 15%;
        }
    </style>
</head>

<body>
    <header>
    </header>


    <footer>
        <p class=''>{{__('Generated By - '). auth()->user()->name}} {{__('on the ')}} - {{__('Copyright')}} &copy; {{config('app.name')}} {{now()->year}}</p>
    </footer>


    <div class=''>
        <div class='' style="padding-bottom: 10px;">
            <div style="float: left; width: 40%; ">
                <img src="{{'data:image/png;base64,'.base64_encode(file_get_contents(public_path('img/logo.jpg')))}}" alt='' style="width:auto;height:100px;">
                <p style="margin-top: -22px; padding-left:15px;">{{__('B.P. 3462')}} {{__('Douala')}} - {{__('Cameroon')}} {{__('Tel:')}} +237 233 433 88 88 /
                    <br> 42 71 09 / 699 90 65 68 / 699 92 63 62 <br> {{__("FAX")}} +237 233 42 71 62 {{__('site web')}} : www.groupe-cible.com
                </p>
            </div>

            <p style="margin-left: 63%; width: 35%; ">
                <span style="font-size: x-larger; font-weight:bolder; ">{{__('ATTACHEMENT')}} <small style="font-size: small; color:red;">{{\Str::random(10)}}</small></span>
                <br />{{__('Period From')}} {{ now()->month($month)->startOfMonth()->ISOFormat('LL')}} {{__('to')}} {{ now()->month($month)->endOfMonth()->ISOFormat('LL') }}
                <br />{{__('Client')}} : {{!is_null($company) ? $company->name : ''}}
                <br>{{__('departments.department')}} : {{!is_null($department) ? $department->name : ''}}
            </p>
        </div>
        <table class="table">
            <thead class="bg-primary text-white">
                <tr>
                    <th>{{ __('Employee Name') }}</th>
                    <th>{{ __('Qualification') }}</th>
                    @foreach ($dates as $date)
                    <th>{{ $date->day }}</th>
                    @endforeach
                </tr>
            </thead>
            <tbody>
                @foreach ($users as $user)
                <tr>
                    <td>{{$user->name}}</td>
                    <td>{{$user->position}}</td>

                    @foreach ($dates as $day)
                    <td>
                        {{$user->getHoursWorked($day,$month)}}
                    </td>
                    @endforeach
                </tr>
                @endforeach
            </tbody>
        </table>
        <div class='' style="margin-left: 80%; padding-left:3px;">
            <div>
                @if(!empty($supervisor))
                <h4>{{ucwords($supervisor->name)}}</h4>
                @if(!is_null($supervisor->signature_path))
                <div class="w-25 h-25">
                    <img src="{{'data:image/png;base64,'.base64_encode(file_get_contents(asset('storage/attachments/'.$supervisor->signature_path)))}}" alt=''>
                </div>
                <p>{{__("Date")}} {{now()->format('Y-m-d')}}</p>
                @endif
                @else
                <p style="padding-top:5px">
                    {{ __("No assigned supervisor")}}
                </p>
                @endif
            </div>
        </div>
    </div>
    <div class="iso-logo">
        <img src="{{'data:image/png;base64,'.base64_encode(file_get_contents(public_path('img/iso-logo.jpeg')))}}" alt='' style="width:auto;height:300px;">
    </div>

</body>

</html>