<!DOCTYPE html>
<html>

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>{{ __('reports.overtime_report').now()->IsoFormat('LL')}}</title>

    <style type="text/css">
        @page {
            margin: 0cm 0cm;
        }

        /** Define now the real margins of every page in the PDF **/
        body {
            margin-top: 0.3cm;
            margin-left: 0.5cm;
            margin-right: 0.5cm;
            margin-bottom: 0cm;
        }

        /** Define the header rules **/
        header {
            position: fixed;
            top: 0cm;
            left: 0cm;
            right: 0cm;
            height: 0.1cm;

            /** Extra personal styles **/
            background-color: #17469E;
        }

        /** Define the footer rules **/
        footer {
            position: fixed;
            bottom: 0cm;
            left: 0cm;
            right: 0cm;
            height: 2cm;

            /** Extra personal styles **/
            text-align: center;
            font-size: medium;
            line-height: 1.5cm;
            border-bottom: 2px solid #17469E;
        }

        .iso-logo {
            position: fixed;
            bottom: 3cm;
            right: .8cm;
            height: 3.2cm;
        }

        .heading {
            font-family: Arial, Helvetica, sans-serif;
            font-size: 22px;
            font-weight: 800;
            padding-bottom: 0;
        }

        .sub-heading {
            font-family: Arial, Helvetica, sans-serif;
            font-size: 14px;
            font-weight: 500;
            padding-bottom: 2px;
        }

        .badge {
            display: inline-block;
            padding: 0.35em 0.65em;
            font-size: .75em;
            font-weight: 400;
            line-height: 1;
            color: #fff;
            text-align: center;
            white-space: nowrap;
            vertical-align: baseline;
            border-radius: 0.25rem;
        }

        .bg-danger {
            background-color: #d32f2f !important;
        }

        .bg-success {
            background-color: #2e7d32 !important;
        }

        .bg-warning {
            background-color: #ffb300 !important;
        }

        .bg-primary {
            background-color: #17469E !important;
        }

        .text-white {
            color: white;
        }

        .table {
            font-family: Arial, Helvetica, sans-serif;
            font-size: 13px;
            border-collapse: collapse;
            width: 100%;
            margin-top: 20px;
            margin-bottom: 1.5cm;
        }

        td,
        th {
            border: 1px solid #ddd;
            padding: 8px;
        }

        tr:nth-child(even) {
            background-color: #f2f2f2;
        }

        .table th {
            padding-top: 10px;
            padding-bottom: 10px;
            text-align: left;
            background-color: #17469E;
            color: white;
        }

        .summary-table {
            font-family: Arial, Helvetica, sans-serif;
            font-size: 13px;
            border-collapse: collapse;
            width: 80%;
        }

        .summary-table td,
        .summary-table th {
            border: 1px solid #ddd;
            text-align: left;
        }

        .fs-bold {
            font-weight: 600;
            font-size: 18px;
        }

        .w-25 {
            width: 25%;
        }

        .h-25 {
            height: 25%;
        }

        .text-underline {
            text-decoration: underline;
        }
    </style>
</head>

<body>
    <header>
    </header>


    <footer>
        <p class=''>{{__('Generated By - '). auth()->user()->name}} {{__('on the ')}} - {{__('Copyright')}} &copy; {{config('app.name')}} {{now()->year}}</p>
    </footer>


    <div class=''>
        <div class='' style="padding-bottom: 10px;">
            <div style="float: left; width: 40%; ">
                <img src="{{'data:image/png;base64,'.base64_encode(file_get_contents(public_path('img/logo.jpg')))}}" alt='' style="width:auto;height:100px;">
                <p style="margin-top: -22px; padding-left:15px; font-size:smaller;">{{__('B.P. 3462')}} {{__('Douala')}} - {{__('Cameroon')}} {{__('Tel:')}} +237 233 433 88 88 /
                    42 71 09 / 699 90 65 68 / 699 92 63 62 <br> {{__("FAX")}} +237 233 42 71 62 {{__('site web')}} : www.groupe-cible.com
                </p>
            </div>

            <p style="margin-left: 63%; width: 38%; font-size:smaller;">
                <span style="font-size: x-larger; font-weight:bolder; ">{{__('ATTACHEMENT')}} <small style="font-size: small; color:red;">{{\Str::random(10)}}</small></span>
                <br />{{__('Period From')}} {{ now()->isoweek($week)->startOfWeek()->ISOFormat('L')}} {{__('to')}} {{ now()->isoweek($week)->endOfWeek()->ISOFormat('L') }}
                <br />{{__('Client')}} : {{!is_null($company) ? $company->name : ''}}
                <br>{{__('departments.department')}} : {{!is_null($department) ? $department->name : ''}}
            </p>
            <p class="text-underline" style="margin-left: 45%; text-align: center; font-weight:bolder; ">{{__("Overtimes Recorded")}}</p>
        </div>

        <table class="table" style="padding-top: 10px;">
            <thead class="bg-primary text-white">
                <tr>
                    <th>{{ __('employees.employee_name') }}</th>
                    <th>{{ __('employees.qualification') }}</th>
                    <th>{{__('employees.t_hours_worked')}}</th>
                    <th>{{__('employees.signature')}}</th>
                    <th>{{__('120%')}}</th>
                    <th>{{__('130%')}}</th>
                    <th>{{__('140%')}}</th>
                    <th>{{__('150%')}}</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($users as $user)
                @php
                $workdays_overtime = $user->overtimes->map(function($overtime){
                if($overtime->start_time->dayOfWeek != Carbon\Carbon::SUNDAY){
                return [
                'day' => $overtime->start_time->format('Y-m-d'),
                'minutes_worked' => $overtime->minutes_worked,
                ];
                }
                })->filter(function($overtime){
                return !empty($overtime);
                })->sum('minutes_worked');
                @endphp
                <tr>
                    <td>{{$user->name}}</td>
                    <td>{{$user->position}}</td>
                    <td>{{intdiv($user->overtimes->sum('minutes_worked'), 60).':'. ($user->overtimes->sum('minutes_worked') % 60); }}</td>
                    <td>
                        @if(!is_null($user->signature_path))
                        <div>
                            <img src="{{'data:image/png;base64,'.base64_encode(file_get_contents(asset('storage/attachments/'.$user->signature_path)))}}" alt='' style="width:auto;height:50px;">
                        </div>
                        @else
                        {{__('common.confirm')}}
                        @endif
                    </td>
                    <td>
                        @php
                        if($workdays_overtime - 480 >= 0 ){
                        $workdays_overtime = $workdays_overtime - 480;
                        echo '8';
                        }else{
                        echo intdiv($workdays_overtime, 60) .":". ($workdays_overtime % 60);
                        }
                        @endphp
                    </td>
                    <td>
                        @php
                        if($workdays_overtime > 480) {
                        if($workdays_overtime - 480 >= 0){
                        $workdays_overtime = $workdays_overtime - 480;
                        echo '8';
                        }else{
                        echo intdiv($workdays_overtime, 60) .":". ($workdays_overtime % 60);
                        }
                        }else {
                        echo intdiv($workdays_overtime, 60) .":". ($workdays_overtime % 60);
                        }
                        @endphp
                    </td>
                    <td>
                        @php
                        echo intdiv($workdays_overtime, 60) .":". ($workdays_overtime % 60); 
                        @endphp
                    </td>
                    <td>
                        @php
                        $user->overtimes->map(function($overtime){
                        if($overtime->start_time->dayOfWeek == Carbon\Carbon::SUNDAY){
                        echo intdiv($overtime->minutes_worked, 60) .":". ($overtime->minutes_worked % 60);
                        }
                        });
                        @endphp
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
        <div class='' style="margin-left: 70%; padding-left:3px;">
            <div style="text-align: left;">
                @if(!empty($supervisor))
                <h4>{{ucwords($supervisor->name)}}</h4>
                @if(!is_null($supervisor->signature_path))
                <div class="">
                    <img src="{{'data:image/png;base64,'.base64_encode(file_get_contents(asset('storage/attachments/'.$supervisor->signature_path)))}}" alt='' style="width:auto;height:100px;">
                </div>
                <p>{{__("Date")}} {{now()->format('Y-m-d')}}</p>
                @endif
                @else
                <p style="padding-top:5px">
                    {{ __('departments.no_assigned_supervisor')}}
                </p>
                @endif
            </div>
        </div>
    </div>
    <div class="iso-logo">
        <img src="{{'data:image/png;base64,'.base64_encode(file_get_contents(public_path('img/iso-logo.jpeg')))}}" alt='' style="width:auto;height:250px;">
    </div>

</body>

</html>